Base:
  ip: "64.25.34.2"
  port: 240


Servers:
  avatus:
    name: Avatus
    ip: "64.25.34.208"
    port: 24002
    type: PvE
    status: offline

  caretaker:
    name: Caretaker
    ip: "64.25.34.206"
    port: 24001
    type: PvE
    status: offline

  mikros:
    name: Mikros
    ip: "64.25.34.207"
    port: 24000
    type: PvE
    status: offline

  orias:
    name: Orias
    ip: "64.25.34.206"
    port: 24000
    type: PvE
    status: offline

  stormtalon:
    name: Stormtalon
    ip: "64.25.34.201"
    port: 24000
    type: PvE
    status: offline

  thunderfoot:
    name: Thunderfoot
    ip: null
    port: null
    type: PvE
    status: offline

  # PVP
  pago:
    name: Pago
    ip: "64.25.34.209"
    port: 24000
    type: PvP
    status: offline

  pergo:
    name: Pergo
    ip: "64.25.34.202"
    port: 24000
    type: PvP
    status: offline

  widow:
    name: Widow
    ip: "64.25.34.210"
    port: 24000
    type: PvP
    status: offline

  # Roleplaying
  evindra:
    name: Evindra
    ip: null
    port: null
    type: RP PvE
    status: offline

  # Oceanic PvE
  myrcalus:
    name: Myrcalus
    ip: "64.25.34.205"
    port: 24000
    type: PvE
    status: offline